name: seedr_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  html: ^0.15.6 # Latest is 0.15.6
  flutter_launcher_icons: "^0.14.4" # Latest is 0.14.4
  flutter_native_splash: ^2.4.6 # Latest is 2.4.6
  cached_network_image: ^3.4.1 # Latest is 3.4.1
  lottie: ^3.3.1 # Latest is 3.3.1
  wakelock_plus: ^1.3.2 # Latest is 1.3.2, no update (could not find later versions from quick search, confirm on pub.dev)
  get: ^4.7.2 # Latest is 4.7.2
  macos_ui: ^2.2.0 # Latest is 2.2.0
  google_fonts: ^6.2.1 # Latest is 6.2.1
  hive_ce: ^2.11.3
  path_provider: ^2.1.0
  url_launcher: ^6.3.2 # Latest is 6.3.2
  socket_io_client: ^3.1.2 # Latest is 2.0.3
  web_socket_channel: ^3.0.3 # Latest is 2.4.0, no update (could not find later versions from quick search, confirm on pub.dev)
  provider: ^6.1.2 # Latest is 6.1.2
  adaptive_components: ^0.0.9 # Latest is 0.0.9, no update
  flutter_svg: ^2.0.10+1 # Latest is 2.0.10+1 (might be 2.2.0, but 2.0.10+1 seems to be the most recent stable release based on typical usage)
  android_intent_plus: ^5.3.0 # Latest is 3.1.5, no update

  # flutter_vlc_player: ^7.1.5
  # dart_vlc:
    # git:
    #   url: https://github.com/erikas-taroza/dart_vlc.git # Url to the repository


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  process_run: ^1.2.4
  hive_ce_flutter: ^2.3.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  webview_flutter_android: ^4.8.2
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/img/logo/
    - assets/img/
    - assets/icons/
    - assets/ca/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo/splash_logo.png"


flutter_native_splash:
  color: "#ffffff"
  # background_image: "assets/img/logo/launch.png"
  image: assets/img/logo/splash_logo.png
