version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter -v build apk 
   
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
