name: Flutter CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # or 'zulu' if you prefer that vendor
          java-version: '21.0.7'


      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'
          channel: 'stable'

      - run: flutter pub get

      - run: flutter build apk

      - run: flutter build windows

      # - name: Extract mpv files
      #   run: 7z x mpc_paste_in_build.7z

      - name: Rename APK for release
        run: |
          mkdir -p release-apk
          cp build/app/outputs/flutter-apk/app-release.apk release-apk/TorFlix-${{ github.ref_name }}.apk

      - name: Archive Windows Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: TorFlix-${{ github.ref_name }}-windows.zip
          directory: build/windows/x64/runner/Release

      - name: Push GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            release-apk/TorFlix-${{ github.ref_name }}.apk,
            build/windows/runner/Release/TorFlix-${{ github.ref_name }}-windows.zip
          token: ${{ secrets.TOKEN }}
          tag: 1.0.${{ github.run_number }}
